### ISSUE TITLE
Add an example of an Agent using Polygon

### ISSUE THREAD

**Issue by Gonmeso** [gizatechxyz/actions-sdk#33]
Currently we have an example of agents working with Arbitrum ([see notebook](https://github.com/gizatechxyz/actions-sdk/blob/main/examples/agents/using_arbitrum.ipynb)).

The idea will be to create another example using Polygon instead of Arbitrum, for this it will be good to check the [ape-polygon](https://github.com/ApeWorX/ape-polygon) plugin as it should be necessary to install it to use it with ape.

This should come in a form of a notebook and add it in the `examples/agents/` folder. Once merged this tutorial will be added to the official documentation!

**Comment by silent-cipher** [comment]
@Gonmeso , Can you assign this issue to me?
